grid_map_topic: /grid_map_node/grid_map
grid_map_visualizations:
  - name: elevation_points
    type: point_cloud
    params:
     layer: obstacles
  - name: elevation_grid
    type: occupancy_grid
    params:
     layer: obstacles
     data_min: 0.08
     data_max: -0.16
